[package]
name = "jocky-runtime"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
jocky-ast = { path = "../ast" }
jocky-ir = { path = "../ir" }
serde_json.workspace = true
time.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
jocky-agent-linux = { path = "../../agent/linux" }

[target.'cfg(target_os = "windows")'.dependencies]
jocky-agent-windows = { path = "../../agent/windows" }
